Create app
Tshobohwa/math-magician pull request #2
Opened 2023-03-28 19:28 UTC by Tshobohwa

# FEATURE ADDED 
- [ ] Creation of the user interface of the app.

2023-03-28 19:38 UTC, AnselemOdims requested changes
### Hi @Tshobohwa , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-28 19:38 UTC, AnselemOdims commented on src/components/Keyboard.js
> +      </button>
- [ ] Please kindly ensure that your design follows the color of the buttons in the original design
- [ ] Also, the division operator does not display as it should. See image below for reference

![image](https://user-images.githubusercontent.com/43995830/228348375-da07b8ef-dcb3-4260-bdb1-401fae16ffea.png)

2023-03-29 10:37 UTC, Tshobohwa commented
- [ ] Fixed colors and displayed division sign.

2023-03-29 10:46 UTC, julie-ify approved these changes
Hi @Tshobohwa,

## Highlights!
- Replication of design ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 11:51 UTC, merged